#!/usr/bin/env node
// =============================================================================
// SONGZY — sitemap.xml + robots.txt generator
//
// Scans root *.html + content/blog/*.html, emits sitemap.xml with proper
// priorities + lastmod, and a robots.txt that points to it.
// =============================================================================

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.resolve(__dirname, '..');
const BASE_URL  = process.env.SITE_URL || 'https://songzy.eu';

// Pages we want excluded from the sitemap
const EXCLUDED = new Set([
  'admin.html',
  'order-brief.html',
  'm-song.html',
  'checkout.html',
]);

// Hand-tune priorities for the most important pages
const PRIORITY = {
  'index.html':         { priority: 1.0, changefreq: 'weekly' },
  'wedding-song.html':  { priority: 0.9, changefreq: 'weekly' },
  'anniversary-song.html': { priority: 0.9, changefreq: 'weekly' },
  'memorial-song.html': { priority: 0.8, changefreq: 'weekly' },
  'canzone-personalizzata.html': { priority: 0.9, changefreq: 'weekly' },
  'canzone-matrimonio.html':     { priority: 0.9, changefreq: 'weekly' },
  'about.html':         { priority: 0.5, changefreq: 'monthly' },
  'privacy.html':       { priority: 0.3, changefreq: 'yearly' },
  'terms.html':         { priority: 0.3, changefreq: 'yearly' },
  'refund.html':        { priority: 0.4, changefreq: 'yearly' },
};
const DEFAULT_PAGE_PRIORITY  = { priority: 0.7, changefreq: 'monthly' };
const DEFAULT_BLOG_PRIORITY  = { priority: 0.6, changefreq: 'monthly' };

function urlForFile(file) {
  if (file === 'index.html') return `${BASE_URL}/`;
  // cleanUrls is enabled in vercel.json, so drop .html
  return `${BASE_URL}/${file.replace(/\.html$/, '')}`;
}

async function collectRootHtml() {
  const all = await fs.readdir(ROOT, { withFileTypes: true });
  return all
    .filter((e) => e.isFile() && e.name.endsWith('.html') && !EXCLUDED.has(e.name))
    .map((e) => e.name);
}

async function collectBlogHtml() {
  const blogDir = path.join(ROOT, 'blog');
  try {
    const files = await fs.readdir(blogDir, { withFileTypes: true });
    return files
      .filter((e) => e.isFile() && e.name.endsWith('.html'))
      .map((e) => `blog/${e.name}`);
  } catch (e) {
    return [];
  }
}

async function fileLastmod(rel) {
  try {
    const stat = await fs.stat(path.join(ROOT, rel));
    return stat.mtime.toISOString().split('T')[0];
  } catch (e) {
    return new Date().toISOString().split('T')[0];
  }
}

async function main() {
  const rootHtml = await collectRootHtml();
  const blogHtml = await collectBlogHtml();

  const entries = [];

  for (const file of rootHtml) {
    const cfg = PRIORITY[file] || DEFAULT_PAGE_PRIORITY;
    const lastmod = await fileLastmod(file);
    entries.push({ loc: urlForFile(file), lastmod, ...cfg });
  }

  for (const blog of blogHtml) {
    const cfg = DEFAULT_BLOG_PRIORITY;
    const lastmod = await fileLastmod(blog);
    const slug = path.basename(blog, '.html');
    entries.push({ loc: `${BASE_URL}/blog/${slug}`, lastmod, ...cfg });
  }

  // Sort by priority desc for readability
  entries.sort((a, b) => b.priority - a.priority);

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.map((e) => `  <url>
    <loc>${e.loc}</loc>
    <lastmod>${e.lastmod}</lastmod>
    <changefreq>${e.changefreq}</changefreq>
    <priority>${e.priority.toFixed(1)}</priority>
  </url>`).join('\n')}
</urlset>
`;

  await fs.writeFile(path.join(ROOT, 'sitemap.xml'), xml, 'utf-8');

  const robots = `# Songzy — robots.txt
# Generated by scripts/build-sitemap.mjs

User-agent: *
Allow: /
Disallow: /admin.html
Disallow: /api/admin/
Disallow: /order-brief.html
Disallow: /m-song.html
Disallow: /checkout.html

Sitemap: ${BASE_URL}/sitemap.xml

# Crawl-delay for noisy bots (most reputable crawlers ignore this)
User-agent: SemrushBot
Crawl-delay: 5

User-agent: AhrefsBot
Crawl-delay: 5
`;
  await fs.writeFile(path.join(ROOT, 'robots.txt'), robots, 'utf-8');

  console.log(`[build-sitemap] sitemap.xml: ${entries.length} URLs`);
  console.log(`[build-sitemap] robots.txt: written`);

  // Best-effort ping to Google + Bing (legacy ping endpoints)
  if (!process.env.SITEMAP_NO_PING) {
    const sitemapUrl = encodeURIComponent(`${BASE_URL}/sitemap.xml`);
    const pings = [
      `https://www.google.com/ping?sitemap=${sitemapUrl}`,
      `https://www.bing.com/ping?sitemap=${sitemapUrl}`,
    ];
    for (const url of pings) {
      try {
        const r = await fetch(url, { method: 'GET', signal: AbortSignal.timeout(8000) });
        console.log(`[build-sitemap] ping ${url.split('?')[0]} → ${r.status}`);
      } catch (e) {
        console.warn(`[build-sitemap] ping ${url.split('?')[0]} failed: ${e.message}`);
      }
    }
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
